apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.appName }}
    release: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.deployment.image }}
          env:
            - name: SWKB-back-cs
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deployment.secretName }}
                  key: connstr 
          ports:
            - name: http
              containerPort: {{ .Values.targetPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.deployment.probe.live.linitialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probe.live.periodSeconds  }}
            httpGet:
              path: /config/alive/
              port: http
          readinessProbe:
            httpGet:
              path: /characters/
              port: http
            initialDelaySeconds: {{ .Values.deployment.probe.read.linitialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probe.read.periodSeconds  }}