Deployment:
  Replicas: 1
  Name: swkb-front-prod
  Image: ingafen/swkb-front:latest

Service:
  Type: NodePort
  Name: swkb-front-prod

Autoscaling:
  Enabled: false
  Name: swkb-front-hpa
  MinReplicas: 1
  MaxReplicas: 10
  TargetRAMUtilization: 60

ContainerPort: 887

TargetPort: 80

AppName: swkbfront

backURL: http://swkb-back-prod.prod:888