Deployment:
  Replicas: 1
  Name: swkb-front-test
  Image: ingafen/swkb-front:test

Service:
  Type: NodePort
  Name: swkb-front-test

Autoscaling:
  Enabled: false
  Name: swkb-front-hpa
  MinReplicas: 1
  MaxReplicas: 2
  TargetRAMUtilization: 60

ContainerPort: 887

TargetPort: 80

AppName: swkbfront

backURL: http://swkb-back-test.test:888