apiVersion: apps/v1
kind: Deployment
metadata:
  name: swkb-front-deployment
  labels:
    app: {{ .Values.AppName }}
    chart: helm-swkb
    release: {{ .Release.Service }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.AppName }}
          image: ingafen/swkb-front  
          ports:
            - name: http
              containerPort: {{ .Values.ContainerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http