apiVersion: v1
kind: Service
metadata:
  name: swkb-front-svc
  labels:
    app: {{ .Values.AppName }}
    chart: helm-swkb
    release: {{ .Release.Service }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ServiceType }}
  selector:
    app: {{ .Values.AppName }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ContainerPort }}
      targetPort: {{ .Values.TargetPort }}
      name: http