apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: SWKB-front
  ports:
    - protocol: TCP
      port: {{ .Values.ContainerPort }}
      targetPort: {{ .Values.TargetPort }}