deployment:
  replicas: 1
  name: swkb-back-prod
  image: ingafen/swkb-back:latest
  secretName: cs-prod
  probe:
    initialDelaySeconds: 20
    periodSeconds: 9

service:
  type: NodePort
  name: swkb-back-test
  nodePort: 30777
autoscaling:
  enabled: false
  name: swkb-back-hpa
  minReplicas: 1
  maxReplicas: 10
  targetRAMUtilization: 60

containerPort: 888

targetPort: 80

appName: swkbback