deployment:
  replicas: 1
  name: swkb-back-dev
  image: ingafen/swkb-back:dev
  secretName: cs-dev
  probe:
    live:
      initialDelaySeconds: 30
      periodSeconds: 3
    read:
      initialDelaySeconds: 20
      periodSeconds: 2

service:
  type: NodePort
  name: swkb-back-dev
  nodePort: 31234
autoscaling:
  enabled: true
  name: swkb-back-hpa
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 11

containerPort: 888

targetPort: 80

appName: swkbback