deployment:
  replicas: 1
  name: swkb-back-dev
  image: ingafen/swkb-back

service:
  type: NodePort
  name: swkb-back-dev

autoscaling:
  enabled: false
  name: swkb-back-hpa
  minReplicas: 1
  maxReplicas: 10
  targetRAMUtilization: 60 

containerPort: 80

targetPort: 888

appName: swkbback

connectionString: "Default value"