deployment:
  replicas: 1
  name: swkb-back-dev
  image: ingafen/swkb-back:dev
  secretName: cs-dev
  probe:
    live:
      initialDelaySeconds: 30
      periodSeconds: 10
    read:
      initialDelaySeconds: 20
      periodSeconds: 2

service:
  type: NodePort
  name: swkb-back-dev
  nodePort: 31234
autoscaling:
  enabled: true
  name: swkb-back-hpa
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilization: 15

resources:
  requests:
    memory: "200Mi"
    cpu: "200m"
  limits:
    memory: "300Mi"
    cpu: "400m"

containerPort: 888

targetPort: 80

appName: swkbback