// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarWarsKb.Back.Model;

namespace StarWarsKb.Back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220401065936_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StarWarsKb.Infrastructure.Model.Character", b =>
                {
                    b.Property<int>("StarWarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BirthYear")
                        .HasColumnType("text");

                    b.Property<string>("EyeColor")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HairColor")
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("HomeWorldId")
                        .HasColumnType("integer");

                    b.Property<double>("Mass")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SkinColor")
                        .HasColumnType("text");

                    b.HasKey("StarWarId");

                    b.HasIndex("HomeWorldId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StarWarsKb.Infrastructure.Model.Film", b =>
                {
                    b.Property<int>("StarWarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("StarWarId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("StarWarsKb.Infrastructure.Model.Planet", b =>
                {
                    b.Property<int>("StarWarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("StarWarId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("StarWarsKb.Infrastructure.Model.Starship", b =>
                {
                    b.Property<int>("StarWarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CargoCapacity")
                        .HasColumnType("bigint");

                    b.Property<string>("Consumables")
                        .HasColumnType("text");

                    b.Property<long>("CostInCredits")
                        .HasColumnType("bigint");

                    b.Property<int>("CrewCount")
                        .HasColumnType("integer");

                    b.Property<string>("HyperdriveRating")
                        .HasColumnType("text");

                    b.Property<int>("Lenght")
                        .HasColumnType("integer");

                    b.Property<string>("MGLT")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MaxAtmospheringSpeed")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PassengersCount")
                        .HasColumnType("integer");

                    b.Property<string>("StarshipClass")
                        .HasColumnType("text");

                    b.HasKey("StarWarId");

                    b.ToTable("Starships");
                });

            modelBuilder.Entity("StarWarsKb.Infrastructure.Model.StarshipsCharacters", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("StarshipId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "StarshipId");

                    b.HasIndex("StarshipId");

                    b.ToTable("StarshipsCharacters");
                });

            modelBuilder.Entity("StarWarsKb.Infrastructure.Model.Character", b =>
                {
                    b.HasOne("StarWarsKb.Infrastructure.Model.Planet", "HomeWorld")
                        .WithMany("Residents")
                        .HasForeignKey("HomeWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWarsKb.Infrastructure.Model.StarshipsCharacters", b =>
                {
                    b.HasOne("StarWarsKb.Infrastructure.Model.Character", "Character")
                        .WithMany("StarshipCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsKb.Infrastructure.Model.Starship", "Starship")
                        .WithMany("StarshipsCharacters")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
